name: game_services_firebase_auth
description: This plugin make some FirebaseAuth features available with GameCenter on iOS and PlayGames on Android
version: 0.1.1
homepage: https://github.com/jgrandchavin/game_services_firebase_auth.git
repository: https://github.com/jgrandchavin/game_services_firebase_auth.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.4.0
  firebase_auth: ^3.0.1

  plugin_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: dev.juliengrandchavin.game_services_firebase_auth
        pluginClass: GameServicesFirebaseAuthPlugin
      ios:
        pluginClass: GameServicesFirebaseAuthPlugin